# Generated by Django 3.0 on 2020-01-05 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0003_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='sal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images')),
            ],
        ),
    ]
